language: c

dist: xenial

git:
  depth: false

env:
  - RELEASE_TARBALL="$HOME/nine-${TRAVIS_TAG:-$TRAVIS_COMMIT}.tar.gz"

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:oibaf/graphics-drivers'
      - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
        key_url: 'https://dl.winehq.org/wine-builds/winehq.key'
    packages:
      - gcc-multilib
      # required to update meson
      - python3-pip
      - python3-setuptools
      # winehq releases for winegcc fixes
      - winehq-devel
      - wine-devel-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-dri3-dev
      - libxcb-present-dev
      - libxcb-xfixes0-dev
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libx11-dev:i386
      - libx11-xcb-dev:i386
      - libxcb1-dev:i386
      - libxcb-dri3-dev:i386
      - libxcb-present-dev:i386
      - libxcb-xfixes0-dev:i386
      - libgl1-mesa-dev:i386
      - libegl1-mesa-dev:i386

install:
  # https://github.com/mesonbuild/meson/blob/master/docs/markdown/Continuous-Integration.md#travis-without-docker
  - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip3 install meson

script:
  - ./release.sh -o "$RELEASE_TARBALL" -- -Ddri2=true -Ddistro-independent=true

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$RELEASE_TARBALL"
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    tags: true
